// GENERATED FILE - DO NOT EDIT
// Generated by tools/i18n/i18n.py

const Map<String, String> enUS = {
  // Navbar
  'home': 'home',
  'explore': 'explore',
  'history': 'history',
  'discover': 'discover',

  // Home
  'trending': 'trending',
  'Discover': 'Discover',
  'Action': 'Action',
  'Drama': 'Drama',
  'Romance': 'Romance',
  'Comedy': 'Comedy',
  'Adventure': 'Adventure',
  'Horror': 'Horror',
  'Classic': 'Classic',
  'see all': 'see all',
  'continue watching': 'continue watching',

  // VIP Card
  'vip account': 'VIP ACCOUNT',
  'become a vip member': 'BECOME A VIP MEMBER',
  'exclusive drama': 'exclusive dramas',
  'anytime streaming': 'stream anytime',
  'unlimited viewing': 'unlimited viewing',
  'personal content': 'personal content',
  'upgrade now': 'upgrade now',
  'max. 2 devices': 'Max. 2 devices',

  // Account
  'login': 'login',
  'logout': 'logout',
  'account settings': 'account settings',
  'account': 'account',
  'manage device': 'manage devices',
  'language': 'language',
  'payment & transaction': 'payment & transactions',
  'subscription plan': 'subscription plan',
  'transaction history': 'transaction history',
  'help center': 'help center',
  'privacy policy': 'privacy policy',
  'terms of use': 'terms of use',
  'confirm': 'confirm',
  'are you sure you want to log out?': 'are you sure you want to log out?',
  'no': 'no',
  'yes': 'yes',

  // Subscription
  'subscription': 'subscription',
  'no packages available': 'no packages available',
  'select a package': 'select a package',
  'enjoy all premium content and unlimited access':
      'enjoy all premium content and unlimited access',
  'weekly': 'weekly',
  'monthly': 'monthly',
  'yearly': 'yearly',
  'day': 'day',
  'year': 'year',
  'save': 'save',
  'Access all VIP content': 'Access all VIP content',
  'Premium video quality': 'Premium video quality',

  // History
  'continue where you left off': 'continue where you left off',
  'my list': 'my list',
  'no viewing history yet': 'no viewing history yet',
  'the series or episode you are watching will appear here':
      'The series or episode you are watching will appear here',
  'my list is still empty': 'my list is still empty',
  "save your favorite series so they're easy to find and watch later":
      "Save your favorite series so they're easy to find and watch later",

  'off': 'Off',
  'pilih_paket_vip': 'Pilih Paket VIP',
  'play': 'Play',
  'playing': 'Playing',
  'please_wait': 'Please wait',
  'profileview': 'ProfileView',
  'see_all': 'See All',
  'subscription_data_is_still_loading': 'Subscription data is still loading',
  'unlock_upgrade_to_vip': 'Unlock / Upgrade to VIP',
  'upgrade_now': 'Upgrade Now',
  'vip_episode': 'VIP Episode',
  'welcome': 'WELCOME',
};
