// GENERATED FILE - DO NOT EDIT
// Generated by tools/i18n/i18n.py

const Map<String, String> hiIN = {
  // Navbar
  'home': 'होम',
  'explore': 'एक्सप्लोर',
  'history': 'इतिहास',
  'discover': 'खोजें',

  // Home
  'trending': 'ट्रेंडिंग',
  'Discover': 'खोजें',
  'Action': 'एक्शन',
  'Drama': 'ड्रामा',
  'Romance': 'रोमांस',
  'Comedy': 'कॉमेडी',
  'Adventure': 'एडवेंचर',
  'Horror': 'हॉरर',
  'Classic': 'क्लासिक',
  'see all': 'सभी देखें',
  'continue watching': 'देखना जारी रखें',

  // VIP Card
  'vip account': 'VIP अकाउंट',
  'become a vip member': 'VIP सदस्य बनें',
  'exclusive drama': 'एक्सक्लूसिव ड्रामा',
  'anytime streaming': 'कभी भी स्ट्रीम करें',
  'unlimited viewing': 'अनलिमिटेड व्यूइंग',
  'personal content': 'पर्सनल कंटेंट',
  'upgrade now': 'अभी अपग्रेड करें',
  'max. 2 devices': 'अधिकतम 2 डिवाइस',

  // Account
  'login': 'लॉगिन',
  'logout': 'लॉगआउट',
  'account settings': 'अकाउंट सेटिंग्स',
  'account': 'अकाउंट',
  'manage device': 'डिवाइस प्रबंधित करें',
  'language': 'भाषा',
  'payment & transaction': 'भुगतान और लेनदेन',
  'subscription plan': 'सब्सक्रिप्शन प्लान',
  'transaction history': 'लेनदेन इतिहास',
  'help center': 'सहायता केंद्र',
  'privacy policy': 'गोपनीयता नीति',
  'terms of use': 'उपयोग की शर्तें',
  'confirm': 'पुष्टि करें',
  'are you sure you want to log out?': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
  'no': 'नहीं',
  'yes': 'हाँ',

  // Subscription
  'subscription': 'सब्सक्रिप्शन',
  'no packages available': 'कोई पैकेज उपलब्ध नहीं है',
  'select a package': 'एक पैकेज चुनें',
  'enjoy all premium content and unlimited access':
      'सभी प्रीमियम कंटेंट और अनलिमिटेड एक्सेस का आनंद लें',
  'weekly': 'साप्ताहिक',
  'monthly': 'मासिक',
  'yearly': 'वार्षिक',
  'day': 'दिन',
  'year': 'वर्ष',
  'save': 'बचत',
  'Access all VIP content': 'सभी VIP कंटेंट का एक्सेस',
  'Premium video quality': 'प्रीमियम वीडियो क्वालिटी',

  // History
  'continue where you left off': 'जहाँ आपने छोड़ा था, वहीं से जारी रखें',
  'my list': 'मेरी सूची',
  'no viewing history yet': 'अभी तक कोई देखने का इतिहास नहीं है',
  'the series or episode you are watching will appear here':
      'आप जो सीरीज़ या एपिसोड देख रहे हैं, वह यहाँ दिखाई देगा',
  'my list is still empty': 'मेरी सूची अभी भी खाली है',
  "save your favorite series so they're easy to find and watch later":
      'अपनी पसंदीदा सीरीज़ सेव करें ताकि उन्हें आसानी से ढूँढ सकें और बाद में देख सकें',
};
