// GENERATED FILE - DO NOT EDIT
// Generated by tools/i18n/i18n.py

const Map<String, String> idID = {
  // Navbar
  'home': 'beranda',
  'explore': 'jelajahi',
  'history': 'riwayat',
  'discover': 'temukan',

  // Home
  'trending': 'sedang tren',
  'Discover': 'Temukan',
  'Action': 'Aksi',
  'Drama': 'Drama',
  'Romance': 'Percintaan',
  'Comedy': 'Komedi',
  'Adventure': 'Petualangan',
  'Horror': 'Horor',
  'Classic': 'Klasik',
  'see all': 'lihat semua',
  'continue watching': 'lanjutkan menonton',

  // VIP Card
  'vip account': 'akun vip',
  'become a vip member': 'menjadi anggota VIP',
  'exclusive drama': 'drama eksklusif',
  'anytime streaming': 'streaming kapanpun',
  'unlimited viewing': 'akses tontonan tanpa batas',
  'personal content': 'konten pribadi',
  'upgrade now': 'tingkatkan sekarang',
  'max. 2 devices': 'Maks. 2 perangkat',

  // Account
  'login': 'masuk',
  'logout': 'keluar',
  'account settings': 'pengaturan akun',
  'account': 'akun',
  'manage device': 'kelola Perangkat',
  'language': 'bahasa',
  'payment & transaction': 'transaksi & pembayaran',
  'subscription plan': 'paket berlangganan',
  'transaction history': 'riwayat transaksi',
  'help center': 'pusat bantuan',
  'privacy policy': 'kebijakan privasi',
  'terms of use': 'ketentuan penggunaan',
  'confirm': 'konfirmasi',
  'are you sure you want to log out?': 'apakah Anda yakin ingin keluar?',
  'no': 'tidak',
  'yes': 'ya',

  // Subscription
  'subscription': 'berlangganan',
  'no packages available': 'tidak ada paket tersedia',
  'select a package': 'pilih paket',
  'enjoy all premium content and unlimited access':
      'nikmati semua konten premium dan akses tanpa batas',
  'weekly': 'mingguan',
  'monthly': 'bulanan',
  'yearly': 'tahunan',
  'day': 'hari',
  'year': 'tahun',
  'save': 'hemat',
  'Access all VIP content': 'Akses semua konten VIP',
  'Premium video quality': 'kualitas video premium',
  'Unlimited viewing': 'Tanpa batas menonton',
  'limited time promotional price': 'harga promo terbatas',

  // History
  'continue where you left off':
      'lanjutkan dari bagian terakhir yang Anda tonton',
  'my list': 'daftar saya',
  'no viewing history yet': 'belum ada riwayat tontonan',
  'the series or episode you are watching will appear here':
      'series atau episode yang kamu tonton akan muncul di sini',
  'my list is still empty': 'daftar saya masih kosong',
  "save your favorite series so they're easy to find and watch later":
      'simpan series favoritmu agar mudah ditemukan dan ditonton nanti',

  'apple_login_belum_tersedia': 'Apple Login belum tersedia',
  'become_a_vip_member': 'Menjadi Anggota VIP',
  'bookmarkview': 'Bookmark Tampilan',
  'coming_soon': 'Segera datang.',
  'dmn_play': 'DMN Play',
  'episodes': 'Episode',
  'episodeview': 'EpisodeView',
  'facebook_login_belum_tersedia': 'Facebook Login belum tersedia',
  'historyview': 'HistoryView',
  'later': 'Nanti',
  'log in to enjoy all DMN Play features':
      'Log masuk untuk menikmati seluruh fitur DMN Play',
  'off': 'Mati',
  'pilih_paket_vip': 'Pilih Paket VIP',
  'play': 'Putar',
  'playing': 'Memutar',
  'please_wait': 'Mohon tunggu',
  'profileview': 'ProfileView',
  'see_all': 'Lihat Semua',
  'subscription_data_is_still_loading': 'Data berlangganan masih dimuat',
  'unlock_upgrade_to_vip': 'Buka kunci / Upgrade ke VIP',
  'upgrade_now': 'Tingkatkan Sekarang',
  'vip_episode': 'Episode VIP',
  'welcome': 'SELAMAT DATANG',
  'Continue with Google': 'Lanjutkan dengan Google',
  'Continue with Facebook': 'Lanjutkan dengan Facebook',
  'Continue with Apple': 'Lanjutkan dengan Apple',
  'By continuing, you agree to the\nTerms & Conditions and Privacy Policy':
      'Dengan melanjutkan, Anda menyetujui\nSyarat & Ketentuan serta Kebijakan Privasi',
};
