// GENERATED FILE - DO NOT EDIT
// Generated by tools/i18n/i18n.py

const Map<String, String> jaJP = {
  // Navbar
  'home': 'ホーム',
  'explore': '探索',
  'history': '履歴',
  'discover': '見つける',

  // Home
  'trending': 'トレンド',
  'Discover': '見つける',
  'Action': 'アクション',
  'Drama': 'ドラマ',
  'Romance': 'ロマンス',
  'Comedy': 'コメディ',
  'Adventure': 'アドベンチャー',
  'Horror': 'ホラー',
  'Classic': 'クラシック',
  'see all': 'すべて見る',
  'continue watching': '視聴を続ける',

  // VIP Card
  'vip account': 'VIPアカウント',
  'become a vip member': 'VIPメンバーになる',
  'exclusive drama': '限定ドラマ',
  'anytime streaming': 'いつでもストリーミング',
  'unlimited viewing': '無制限で視聴',
  'personal content': '限定コンテンツ',
  'upgrade now': '今すぐアップグレード',
  'max. 2 devices': '最大2台のデバイス',

  // Account
  'login': 'ログイン',
  'logout': 'ログアウト',
  'account settings': 'アカウント設定',
  'account': 'アカウント',
  'manage device': 'デバイス管理',
  'language': '言語',
  'payment & transaction': '支払いと取引',
  'subscription plan': 'サブスクリプションプラン',
  'transaction history': '取引履歴',
  'help center': 'ヘルプセンター',
  'privacy policy': 'プライバシーポリシー',
  'terms of use': '利用規約',
  'confirm': '確認',
  'are you sure you want to log out?': 'ログアウトしてもよろしいですか？',
  'no': 'いいえ',
  'yes': 'はい',

  // Subscription
  'subscription': 'サブスクリプション',
  'no packages available': '利用可能なプランはありません',
  'select a package': 'プランを選択',
  'enjoy all premium content and unlimited access':
      'すべてのプレミアムコンテンツと無制限アクセスをお楽しみください',
  'weekly': '週間',
  'monthly': '月間',
  'yearly': '年間',
  'day': '日',
  'year': '年',
  'save': 'お得',
  'Access all VIP content': 'すべてのVIPコンテンツにアクセス',
  'Premium video quality': 'プレミアム画質',

  // History
  'continue where you left off': '前回の続きから視聴',
  'my list': 'マイリスト',
  'no viewing history yet': '視聴履歴はまだありません',
  'the series or episode you are watching will appear here':
      '視聴中のシリーズやエピソードがここに表示されます',
  'my list is still empty': 'マイリストはまだ空です',
  "save your favorite series so they're easy to find and watch later":
      'お気に入りのシリーズを保存して、後から簡単に見つけて視聴できます',
};
