// GENERATED FILE - DO NOT EDIT
// Generated by tools/i18n/i18n.py

const Map<String, String> koKR = {
  // Navbar
  'home': '홈',
  'explore': '탐색',
  'history': '시청 기록',
  'discover': '발견',

  // Home
  'trending': '인기',
  'Discover': '발견',
  'Action': '액션',
  'Drama': '드라마',
  'Romance': '로맨스',
  'Comedy': '코미디',
  'Adventure': '어드벤처',
  'Horror': '호러',
  'Classic': '클래식',
  'see all': '모두 보기',
  'continue watching': '계속 시청하기',

  // VIP Card
  'vip account': 'VIP 계정',
  'become a vip member': 'VIP 회원이 되어보세요',
  'exclusive drama': '독점 드라마',
  'anytime streaming': '언제든지 스트리밍',
  'unlimited viewing': '무제한 시청',
  'personal content': '개인 콘텐츠',
  'upgrade now': '지금 업그레이드',
  'max. 2 devices': '최대 2대의 기기',

  // Account
  'login': '로그인',
  'logout': '로그아웃',
  'account settings': '계정 설정',
  'account': '계정',
  'manage device': '기기 관리',
  'language': '언어',
  'payment & transaction': '결제 및 거래',
  'subscription plan': '구독 플랜',
  'transaction history': '거래 내역',
  'help center': '고객센터',
  'privacy policy': '개인정보 처리방침',
  'terms of use': '이용약관',
  'confirm': '확인',
  'are you sure you want to log out?': '정말 로그아웃하시겠습니까?',
  'no': '아니요',
  'yes': '예',

  // Subscription
  'subscription': '구독',
  'no packages available': '이용 가능한 패키지가 없습니다',
  'select a package': '패키지를 선택하세요',
  'enjoy all premium content and unlimited access':
      '모든 프리미엄 콘텐츠와 무제한 이용을 즐겨보세요',
  'weekly': '주간',
  'monthly': '월간',
  'yearly': '연간',
  'day': '일',
  'year': '년',
  'save': '할인',
  'Access all VIP content': '모든 VIP 콘텐츠 이용',
  'Premium video quality': '프리미엄 화질',

  // History
  'continue where you left off': '마지막으로 시청한 부분부터 계속하기',
  'my list': '내 목록',
  'no viewing history yet': '아직 시청 기록이 없습니다',
  'the series or episode you are watching will appear here':
      '시청 중인 시리즈나 에피소드가 여기에 표시됩니다',
  'my list is still empty': '내 목록이 아직 비어 있습니다',
  "save your favorite series so they're easy to find and watch later":
      '좋아하는 시리즈를 저장하여 나중에 쉽게 찾아 시청하세요',
};
