// GENERATED FILE - DO NOT EDIT
// Generated by tools/i18n/i18n.py

const Map<String, String> msMY = {
  // Navbar
  'home': 'Laman Utama',
  'explore': 'Terokai',
  'history': 'Sejarah',
  'discover': 'Temui',

  // Home
  'trending': 'Sedang Trend',
  'Discover': 'Temui',
  'Action': 'Aksi',
  'Drama': 'Drama',
  'Romance': 'Romantik',
  'Comedy': 'Komedi',
  'Adventure': 'Pengembaraan',
  'Horror': 'Seram',
  'Classic': 'Klasik',
  'see all': 'Lihat Semua',
  'continue watching': 'Teruskan Menonton',

  // VIP Card
  'vip account': 'Akaun VIP',
  'become a vip member': 'Jadi Ahli VIP',
  'exclusive drama': 'Drama Eksklusif',
  'anytime streaming': 'Strim Bila-bila Masa',
  'unlimited viewing': 'Tontonan Tanpa Had',
  'personal content': 'Kandungan Peribadi',
  'upgrade now': 'Naik Taraf Sekarang',
  'max. 2 devices': 'Maks. 2 Peranti',

  // Account
  'login': 'Log Masuk',
  'logout': 'Log Keluar',
  'account settings': 'Tetapan Akaun',
  'account': 'Akaun',
  'manage device': 'Urus Peranti',
  'language': 'Bahasa',
  'payment & transaction': 'Pembayaran & Transaksi',
  'subscription plan': 'Pelan Langganan',
  'transaction history': 'Sejarah Transaksi',
  'help center': 'Pusat Bantuan',
  'privacy policy': 'Dasar Privasi',
  'terms of use': 'Terma Penggunaan',
  'confirm': 'Sahkan',
  'are you sure you want to log out?': 'Adakah anda pasti mahu log keluar?',
  'no': 'Tidak',
  'yes': 'Ya',

  // Subscription
  'subscription': 'Langganan',
  'no packages available': 'Tiada pakej tersedia',
  'select a package': 'Pilih Pakej',
  'enjoy all premium content and unlimited access':
      'Nikmati semua kandungan premium dan akses tanpa had',
  'weekly': 'Mingguan',
  'monthly': 'Bulanan',
  'yearly': 'Tahunan',
  'day': 'Hari',
  'year': 'Tahun',
  'save': 'Jimat',
  'Access all VIP content': 'Akses semua kandungan VIP',
  'Premium video quality': 'Kualiti video premium',

  // History
  'continue where you left off':
      'Teruskan dari tempat terakhir anda berhenti menonton',
  'my list': 'Senarai Saya',
  'no viewing history yet': 'Tiada sejarah tontonan lagi',
  'the series or episode you are watching will appear here':
      'Siri atau episod yang anda tonton akan dipaparkan di sini',
  'my list is still empty': 'Senarai saya masih kosong',
  "save your favorite series so they're easy to find and watch later":
      'Simpan siri kegemaran anda supaya mudah dicari dan ditonton kemudian',
};
